// =============================================
//  COMMUNITY MAKERS' MARKET — DATA (v3)
// =============================================
var CMM_DATA = {

  // ── BUSINESS IDEAS ────────────────────────────
  businessIdeas: [
    { id: 1,  title: "Homemade Pickles & Chutneys",        category: "cooking",   difficulty: "beginner",     investment: "₹500–2,000",     profit: "₹5,000–15,000/mo",   demand: "high",      icon: "🥫", desc: "Traditional recipes using local produce. Sell in local markets, online, or bulk orders for restaurants.", tags: ["food","no-equipment","women-friendly"] },
    { id: 2,  title: "Handmade Jewellery",                 category: "jewelry",   difficulty: "beginner",     investment: "₹1,000–5,000",   profit: "₹8,000–25,000/mo",   demand: "high",      icon: "💍", desc: "Beaded, wire-wrapped, or clay jewellery with unique designs. Huge demand on Instagram and local festivals.", tags: ["craft","festive","gifting"] },
    { id: 3,  title: "Embroidery & Stitching",             category: "tailoring", difficulty: "intermediate", investment: "₹2,000–8,000",   profit: "₹10,000–30,000/mo",  demand: "high",      icon: "🧵", desc: "Custom embroidery on kurtis, dupattas, and home furnishings. Bridal season demand is very high.", tags: ["skilled","seasonal","bridal"] },
    { id: 4,  title: "Clay & Terracotta Products",         category: "crafting",  difficulty: "beginner",     investment: "₹1,500–4,000",   profit: "₹6,000–18,000/mo",   demand: "medium",    icon: "🏺", desc: "Eco-friendly pots, décor, and idols. Growing demand for handmade sustainable products.", tags: ["eco","sustainable","festive"] },
    { id: 5,  title: "Tiffin / Meal Delivery Service",     category: "cooking",   difficulty: "beginner",     investment: "₹2,000–5,000",   profit: "₹15,000–40,000/mo",  demand: "very-high", icon: "🍱", desc: "Home-cooked meals for office workers and students. Subscription model ensures steady income.", tags: ["food","daily-income","women-friendly"] },
    { id: 6,  title: "Handmade Candles & Soaps",           category: "crafting",  difficulty: "beginner",     investment: "₹1,000–3,000",   profit: "₹6,000–20,000/mo",   demand: "high",      icon: "🕯️", desc: "Scented soy candles and herbal soaps. Premium packaging increases perceived value and pricing.", tags: ["gifting","wellness","export-potential"] },
    { id: 7,  title: "Traditional Rangoli & Kolam Art",    category: "painting",  difficulty: "beginner",     investment: "₹500–2,000",     profit: "₹5,000–12,000/mo",   demand: "medium",    icon: "🎨", desc: "Teach online classes or sell pre-made colour rangoli kits and stencils. Festive season peaks.", tags: ["cultural","teaching","seasonal"] },
    { id: 8,  title: "Crochet & Knitting Products",        category: "crafting",  difficulty: "intermediate", investment: "₹2,000–5,000",   profit: "₹8,000–22,000/mo",   demand: "medium",    icon: "🧶", desc: "Bags, baby clothes, décor items and winter wear. Very popular on Etsy and social media.", tags: ["craft","export-potential","gifting"] },
    { id: 9,  title: "Digital Art & Illustration",         category: "painting",  difficulty: "intermediate", investment: "₹0–5,000",       profit: "₹10,000–50,000/mo",  demand: "high",      icon: "🖥️", desc: "Custom portraits, wedding invitations, logo design for small businesses using free apps.", tags: ["digital","students","zero-inventory"] },
    { id: 10, title: "Silk Thread Jewellery",              category: "jewelry",   difficulty: "beginner",     investment: "₹800–2,500",     profit: "₹6,000–18,000/mo",   demand: "high",      icon: "🧿", desc: "Traditional South Indian silk thread bangles and earrings. Very popular for cultural events.", tags: ["cultural","south-indian","gifting"] },
    { id: 11, title: "Homemade Bakery & Sweets",           category: "cooking",   difficulty: "intermediate", investment: "₹3,000–10,000",  profit: "₹12,000–35,000/mo",  demand: "very-high", icon: "🎂", desc: "Cakes, cookies, ladoos, and festival sweets. Custom order cakes are premium-priced.", tags: ["food","festive","gifting"] },
    { id: 12, title: "Fabric Painting & Block Printing",   category: "painting",  difficulty: "intermediate", investment: "₹2,000–6,000",   profit: "₹8,000–25,000/mo",   demand: "medium",    icon: "👘", desc: "Hand-painted sarees, kurtis and tote bags. Unique artistic pieces command high prices.", tags: ["art","fashion","export-potential"] },
    { id: 13, title: "Mehendi (Henna) Artist",             category: "crafting",  difficulty: "intermediate", investment: "₹500–2,000",     profit: "₹10,000–30,000/mo",  demand: "high",      icon: "🌿", desc: "Bridal and festive mehendi services. Home visits and event bookings for consistent income.", tags: ["skilled","bridal","events"] },
    { id: 14, title: "Paper Craft & Origami Products",     category: "crafting",  difficulty: "beginner",     investment: "₹500–1,500",     profit: "₹4,000–12,000/mo",   demand: "medium",    icon: "📦", desc: "Gift boxes, greeting cards, and decorative items. Low investment, high creativity appeal.", tags: ["eco","gifting","zero-waste"] },
    { id: 15, title: "Handloom Weaving",                   category: "tailoring", difficulty: "advanced",     investment: "₹10,000–30,000", profit: "₹20,000–60,000/mo",  demand: "medium",    icon: "🪢", desc: "Traditional handloom sarees and fabrics with GI tag potential. Premium market and export opportunities.", tags: ["traditional","skilled","export-potential"] },
    { id: 16, title: "YouTube / Instagram Content Creation", category: "digital", difficulty: "beginner",     investment: "₹0–5,000",       profit: "₹5,000–1,00,000/mo", demand: "very-high", icon: "📱", desc: "Share cooking recipes, craft tutorials, or lifestyle content. Ad revenue and brand deals.", tags: ["digital","students","women-friendly"] },
    { id: 17, title: "Tutoring & Online Classes",          category: "digital",   difficulty: "beginner",     investment: "₹0–2,000",       profit: "₹8,000–30,000/mo",   demand: "very-high", icon: "📚", desc: "Teach academics, languages, yoga, cooking, or music online via Zoom or WhatsApp groups.", tags: ["education","zero-inventory","students"] },
    { id: 18, title: "Bag Making (Jute/Cloth)",            category: "crafting",  difficulty: "beginner",     investment: "₹1,000–4,000",   profit: "₹5,000–15,000/mo",   demand: "high",      icon: "👜", desc: "Eco-friendly jute and canvas bags. Corporates buy in bulk for branding; high repeat orders.", tags: ["eco","bulk-orders","sustainable"] },
    { id: 19, title: "Herbal Products & Organic Skincare", category: "cooking",   difficulty: "intermediate", investment: "₹2,000–8,000",   profit: "₹10,000–40,000/mo",  demand: "very-high", icon: "🌱", desc: "Natural face packs, hair oils, and herbal powders. Growing organic beauty market in India.", tags: ["wellness","women-friendly","export-potential"] },
    { id: 20, title: "Puppet Making & Storytelling",       category: "crafting",  difficulty: "intermediate", investment: "₹1,000–5,000",   profit: "₹5,000–15,000/mo",   demand: "low",       icon: "🎭", desc: "Traditional Tolu Bommalata puppets and educational storytelling kits for schools.", tags: ["cultural","traditional","education"] },
    { id: 21, title: "Photo Editing & Graphic Design",     category: "digital",   difficulty: "beginner",     investment: "₹0–3,000",       profit: "₹8,000–35,000/mo",   demand: "very-high", icon: "🖌️", desc: "Edit photos for small businesses, weddings and social media using free tools like Canva.", tags: ["digital","students","zero-inventory"] },
    { id: 22, title: "Gift Hamper Curation",               category: "crafting",  difficulty: "beginner",     investment: "₹2,000–6,000",   profit: "₹8,000–25,000/mo",   demand: "high",      icon: "🎁", desc: "Curate and package premium gift hampers for festivals, weddings, and corporate events.", tags: ["gifting","festive","bulk-orders"] },
    { id: 23, title: "Macramé Wall Art & Decor",           category: "crafting",  difficulty: "intermediate", investment: "₹1,500–5,000",   profit: "₹8,000–20,000/mo",   demand: "medium",    icon: "🪡", desc: "Trendy macramé wall hangings, plant hangers and table runners. Very popular for home décor.", tags: ["trending","home-decor","export-potential"] },
    { id: 24, title: "Pickled Vegetables & Fermented Foods", category: "cooking", difficulty: "beginner",     investment: "₹1,000–3,000",   profit: "₹6,000–18,000/mo",   demand: "high",      icon: "🥒", desc: "Mango pickle, gongura pachadi, and traditional fermented foods. Health-conscious market growing.", tags: ["food","traditional","health"] },
    { id: 25, title: "Handmade Diyas & Festive Decor",     category: "crafting",  difficulty: "beginner",     investment: "₹500–2,000",     profit: "₹5,000–30,000/mo",   demand: "very-high", icon: "🪔", desc: "Painted clay diyas, torans, and festive decorations. Peak Diwali season business.", tags: ["festive","seasonal","cultural"] },
    { id: 26, title: "Tanjore Painting",                   category: "painting",  difficulty: "advanced",     investment: "₹5,000–15,000",  profit: "₹15,000–50,000/mo",  demand: "medium",    icon: "🖼️", desc: "Traditional Tanjore-style paintings with gold leaf. Premium art for collectors and gifts.", tags: ["traditional","premium","cultural"] },
    { id: 27, title: "Dry Flower & Resin Art",             category: "crafting",  difficulty: "intermediate", investment: "₹2,000–6,000",   profit: "₹8,000–22,000/mo",   demand: "high",      icon: "🌸", desc: "Resin-preserved flowers in jewellery and décor frames. Trendy and very Instagram-worthy.", tags: ["trending","gifting","export-potential"] },
    { id: 28, title: "Namkeen & Snacks Production",        category: "cooking",   difficulty: "beginner",     investment: "₹2,000–8,000",   profit: "₹10,000–30,000/mo",  demand: "very-high", icon: "🥜", desc: "Traditional South Indian snacks like murukku, chivda, and mixture. Great for wholesale.", tags: ["food","bulk-orders","traditional"] },
  ],

  // ── MARKETPLACE PRODUCTS ──────────────────────
  products: [
    {
      id: 1,
      name: "Handmade Silk Thread Bangles Set",
      seller: "Lakshmi Crafts",
      sellerPhone: "919876543210",
      price: 350,
      originalPrice: 500,
      category: "jewelry",
      rating: 4.8,
      reviews: 124,
      image: "marketplace photos/Handmade Silk Thread Bangles Set.jpg",
      emoji: "💛",
      tags: ["silk", "traditional", "set-of-12"],
      desc: "Beautiful handcrafted silk thread bangles in vibrant colours. Set of 12 bangles. Perfect for festivals and weddings.",
      location: "Hyderabad",
      inStock: true,
    },
    {
      id: 2,
      name: "Gongura Pickle — 500g",
      seller: "Amma's Kitchen",
      sellerPhone: "919845321076",
      price: 180,
      originalPrice: 220,
      category: "food",
      rating: 4.9,
      reviews: 256,
      image: "marketplace photos/Gongura Pickle.jpg",
      emoji: "🥫",
      tags: ["organic", "spicy", "andhra-special"],
      desc: "Authentic Andhra-style gongura pachadi made with fresh sorrel leaves. No preservatives. Family recipe passed down 3 generations.",
      location: "Vijayawada",
      inStock: true,
    },
    {
      id: 3,
      name: "Terracotta Wall Hanging Set",
      seller: "Mitti Arts",
      sellerPhone: "919765432100",
      price: 650,
      originalPrice: 900,
      category: "home-decor",
      rating: 4.7,
      reviews: 89,
      image: "marketplace photos/Terracotta Wall Hanging Set.jpg",
      emoji: "🏺",
      tags: ["eco", "handmade", "wall-decor"],
      desc: "Set of 5 handpainted terracotta wall hangings. Each piece is unique. Ideal for living room and pooja room décor.",
      location: "Hyderabad",
      inStock: true,
    },
    {
      id: 4,
      name: "Custom Macrame Wall Art",
      seller: "Knotty Creations",
      sellerPhone: "919823456789",
      price: 1200,
      originalPrice: 1800,
      category: "home-decor",
      rating: 4.6,
      reviews: 67,
      image: "marketplace photos/Custom Macrame Wall Art.jpg",
      emoji: "🪡",
      tags: ["custom", "boho", "wall-decor"],
      desc: "Handwoven macramé wall hanging — 24×36 inches. Custom size and colour available. Ships in 5–7 days.",
      location: "Vizag",
      inStock: true,
    },
    {
      id: 5,
      name: "Handmade Soy Wax Candle Set",
      seller: "Glow & Co.",
      sellerPhone: "919934567891",
      price: 450,
      originalPrice: 600,
      category: "gifting",
      rating: 4.8,
      reviews: 143,
      image: "marketplace photos/Handmade Soy Wax Candle Set.jpg",
      emoji: "🕯️",
      tags: ["soy-wax", "aromatherapy", "gift-ready"],
      desc: "Set of 4 scented soy wax candles — lavender, jasmine, sandalwood & rose. 40-hour burn time each. Gift-boxed.",
      location: "Hyderabad",
      inStock: true,
    },
    {
      id: 6,
      name: "Andhra Murukku — 500g",
      seller: "Snack Empress",
      sellerPhone: "919856789012",
      price: 120,
      originalPrice: 150,
      category: "food",
      rating: 4.9,
      reviews: 312,
      image: "marketplace photos/Andhra Murukku.jpg",
      emoji: "🥜",
      tags: ["snacks", "crispy", "traditional"],
      desc: "Crispy rice flour murukku with sesame and cumin. Made fresh in small batches. No artificial flavours.",
      location: "Vijayawada",
      inStock: true,
    },
    {
      id: 7,
      name: "Herbal Face Pack Kit",
      seller: "Pure Roots",
      sellerPhone: "919812345670",
      price: 380,
      originalPrice: 500,
      category: "beauty",
      rating: 4.7,
      reviews: 198,
      image: "marketplace photos/Herbal Face Pack Kit.jpg",
      emoji: "🌿",
      tags: ["organic", "skin-care", "chemical-free"],
      desc: "5-in-1 herbal face pack kit — multani mitti, neem, turmeric, rose, and sandalwood. Enough for 15–20 applications.",
      location: "Warangal",
      inStock: true,
    },
    {
      id: 8,
      name: "Handpainted Fabric Tote Bag",
      seller: "Thread & Soul",
      sellerPhone: "919867890123",
      price: 299,
      originalPrice: 400,
      category: "fashion",
      rating: 4.6,
      reviews: 75,
      image: "marketplace photos/Handpainted Fabric Tote Bag.jpg",
      emoji: "👜",
      tags: ["hand-painted", "eco-friendly", "unique"],
      desc: "100% cotton canvas tote bag with hand-painted warli art. Each bag is one-of-a-kind. Washable and sturdy.",
      location: "Hyderabad",
      inStock: true,
    },
    {
      id: 9,
      name: "Dry Flower Resin Earrings",
      seller: "Bloom & Resin",
      sellerPhone: "919878901234",
      price: 250,
      originalPrice: 350,
      category: "jewelry",
      rating: 4.8,
      reviews: 156,
      image: "marketplace photos/Dry Flower Resin Earrings.jpg",
      emoji: "🌸",
      tags: ["resin", "floral", "lightweight"],
      desc: "Dainty pressed flower earrings in clear resin. Each pair captures real dried flowers — no two are alike.",
      location: "Hyderabad",
      inStock: true,
    },
    {
      id: 10,
      name: "Festival Gift Hamper",
      seller: "Joy Box",
      sellerPhone: "919889012345",
      price: 799,
      originalPrice: 1100,
      category: "gifting",
      rating: 4.9,
      reviews: 201,
      image: "marketplace photos/Festival Gift Hamper.jpg",
      emoji: "🎁",
      tags: ["premium", "festive", "ready-to-gift"],
      desc: "Premium festival hamper with artisan chocolates, candles, pickles, and hand-painted diyas. Free personalised card.",
      location: "Hyderabad",
      inStock: true,
    },
    {
      id: 11,
      name: "Crochet Baby Booties & Hat Set",
      seller: "Yarn Tales",
      sellerPhone: "919890123456",
      price: 320,
      originalPrice: 450,
      category: "fashion",
      rating: 4.7,
      reviews: 88,
      image: "marketplace photos/Crochet Baby Booties & Hat Set.jpg",
      emoji: "🧶",
      tags: ["baby", "crochet", "handmade"],
      desc: "Soft cotton crochet baby booties and matching hat. Available in 6 colours. Fits newborn to 6 months.",
      location: "Warangal",
      inStock: true,
    },
    {
      id: 12,
      name: "Tanjore Painting Lord Ganesha",
      seller: "Gold Leaf Studio",
      sellerPhone: "919901234567",
      price: 3500,
      originalPrice: 4500,
      category: "art",
      rating: 4.9,
      reviews: 34,
      image: "marketplace photos/Tanjore Painting Lord Ganesha.jpg",
      emoji: "🖼️",
      tags: ["premium", "traditional", "gold-leaf"],
      desc: "Authentic Tanjore painting with 22K gold leaf work. 12×16 inch framed. Certificate of authenticity included.",
      location: "Vijayawada",
      inStock: true,
    },
  ],

  // ── LEARNING MODULES ─────────────────────────
  modules: [
    {
      id: 1,
      title: "Start Your Business",
      titleTe: "మీ వ్యాపారాన్ని ప్రారంభించండి",
      icon: "🚀",
      level: "Beginner",
      duration: "3 hours",
      lessons: [
        { title: "Choosing Your Product",   titleTe: "మీ ఉత్పత్తిని ఎంచుకోండి",   duration: "20 min", type: "video" },
        { title: "Market Research Basics",  titleTe: "మార్కెట్ రీసెర్చ్ ప్రాథమికాలు", duration: "25 min", type: "video" },
        { title: "Pricing Your Products",   titleTe: "మీ ఉత్పత్తులకు ధర నిర్ణయించండి", duration: "30 min", type: "video" },
        { title: "Download: Business Plan", titleTe: "డౌన్‌లోడ్: వ్యాపార ప్రణాళిక",  duration: "5 min",  type: "download" },
        { title: "Quiz: Am I Ready?",       titleTe: "క్విజ్: నేను సిద్ధంగా ఉన్నానా?", duration: "10 min", type: "quiz" },
      ],
    },
    {
      id: 2,
      title: "WhatsApp Marketing",
      titleTe: "వాట్సాప్ మార్కెటింగ్",
      icon: "💬",
      level: "Beginner",
      duration: "2.5 hours",
      lessons: [
        { title: "Setting Up WhatsApp Business", titleTe: "వాట్సాప్ బిజినెస్ సెటప్",      duration: "20 min", type: "video" },
        { title: "Writing Winning Product Captions", titleTe: "ఉత్పత్తి క్యాప్షన్లు రాయండి", duration: "25 min", type: "video" },
        { title: "Building Your Customer List",  titleTe: "కస్టమర్ లిస్ట్ నిర్మించండి",   duration: "20 min", type: "video" },
        { title: "Broadcast List Strategy",      titleTe: "బ్రాడ్‌కాస్ట్ లిస్ట్ వ్యూహం",  duration: "15 min", type: "video" },
        { title: "Download: Message Templates",  titleTe: "డౌన్‌లోడ్: మెసేజ్ టెంప్లేట్లు", duration: "5 min",  type: "download" },
      ],
    },
    {
      id: 3,
      title: "Instagram for Sellers",
      titleTe: "అమ్మకందారులకు ఇన్‌స్టాగ్రామ్",
      icon: "📸",
      level: "Intermediate",
      duration: "4 hours",
      lessons: [
        { title: "Creating a Business Profile",  titleTe: "బిజినెస్ ప్రొఫైల్ సృష్టించండి", duration: "20 min", type: "video" },
        { title: "Product Photography Tips",     titleTe: "ఉత్పత్తి ఫోటోగ్రఫీ చిట్కాలు",   duration: "35 min", type: "video" },
        { title: "Reels That Sell",              titleTe: "అమ్మే రీల్స్",                  duration: "30 min", type: "video" },
        { title: "Hashtag Strategy",             titleTe: "హ్యాష్‌ట్యాగ్ వ్యూహం",          duration: "20 min", type: "video" },
        { title: "Quiz: Instagram Mastery",      titleTe: "క్విజ్: ఇన్‌స్టాగ్రామ్ మాస్టరీ", duration: "10 min", type: "quiz" },
      ],
    },
    {
      id: 4,
      title: "Government Schemes & Loans",
      titleTe: "ప్రభుత్వ పథకాలు & రుణాలు",
      icon: "🏛️",
      level: "Beginner",
      duration: "2 hours",
      lessons: [
        { title: "PMEGP Scheme Overview",        titleTe: "PMEGP పథకం అవలోకనం",         duration: "25 min", type: "video" },
        { title: "Mudra Loan Application Guide", titleTe: "ముద్రా రుణ దరఖాస్తు గైడ్",    duration: "30 min", type: "video" },
        { title: "Stree Nidhi Fund",             titleTe: "స్త్రీ నిధి ఫండ్",             duration: "20 min", type: "video" },
        { title: "Download: Application Forms",  titleTe: "డౌన్‌లోడ్: దరఖాస్తు ఫారమ్లు", duration: "5 min",  type: "download" },
      ],
    },
    {
      id: 5,
      title: "Financial Basics",
      titleTe: "ఆర్థిక ప్రాథమికాలు",
      icon: "💰",
      level: "Intermediate",
      duration: "3.5 hours",
      lessons: [
        { title: "Tracking Income & Expenses",   titleTe: "ఆదాయం & ఖర్చులు ట్రాక్ చేయండి", duration: "30 min", type: "video" },
        { title: "GST for Small Sellers",        titleTe: "చిన్న అమ్మకందారులకు GST",        duration: "25 min", type: "video" },
        { title: "Profit Margin Calculator",     titleTe: "లాభం మార్జిన్ కాలిక్యులేటర్",   duration: "20 min", type: "video" },
        { title: "Download: Excel Templates",    titleTe: "డౌన్‌లోడ్: ఎక్సెల్ టెంప్లేట్లు",  duration: "5 min",  type: "download" },
        { title: "Quiz: Money Matters",          titleTe: "క్విజ్: మనీ మాటర్స్",            duration: "10 min", type: "quiz" },
      ],
    },
  ],

  // ── SUCCESS STORIES ───────────────────────────
  stories: [
    { id: 1, name: "Priya Sharma",    location: "Hyderabad",  revenue: "₹45,000/mo",  product: "Silk Thread Jewellery",  quote: "I started with ₹2,000 and now earn more than my husband. CMM gave me the platform and courage.", image: null, emoji: "💎", category: "jewelry"   },
    { id: 2, name: "Lakshmi Devi",   location: "Vijayawada", revenue: "₹28,000/mo",  product: "Gongura Pickles",        quote: "My grandmother's recipe is now loved across Andhra. I get 50+ orders every month!", image: null, emoji: "🥫", category: "food"      },
    { id: 3, name: "Anitha Reddy",   location: "Warangal",   revenue: "₹62,000/mo",  product: "Handloom Sarees",        quote: "I trained 12 women in my village. Together we run a micro-enterprise from home.", image: null, emoji: "👘", category: "fashion"   },
    { id: 4, name: "Sunita Kumari",  location: "Vizag",      revenue: "₹19,000/mo",  product: "Herbal Skincare",        quote: "No chemicals, no middlemen. Customers trust my ingredients because I share my process openly.", image: null, emoji: "🌿", category: "beauty"    },
    { id: 5, name: "Kavitha Rao",    location: "Guntur",     revenue: "₹35,000/mo",  product: "Custom Cakes & Sweets",  quote: "From one cake a week to 20+ orders! Instagram and WhatsApp changed everything for me.", image: null, emoji: "🎂", category: "food"      },
    { id: 6, name: "Meera Joshi",    location: "Hyderabad",  revenue: "₹41,000/mo",  product: "Macramé & Home Décor",   quote: "I learned macramé during lockdown. Now I ship across India and even to NRIs abroad.", image: null, emoji: "🪡", category: "home-decor" },
  ],

  // ── SCHEMES ───────────────────────────────────
  schemes: [
    { id: 1, name: "PMEGP", fullName: "Prime Minister's Employment Generation Programme", ministry: "MSME", amount: "₹10L–₹25L",  subsidy: "15–35%", eligibility: "18+ years, any Indian citizen",            link: "https://www.kviconline.gov.in/pmegpeportal/" },
    { id: 2, name: "Mudra Loan", fullName: "Pradhan Mantri Mudra Yojana",                ministry: "Finance", amount: "Up to ₹10L", subsidy: "Low interest",eligibility: "Non-farm small business",           link: "https://www.mudra.org.in/" },
    { id: 3, name: "Stree Nidhi", fullName: "Stree Nidhi Credit Cooperative Federation", ministry: "AP/TS Govt", amount: "Up to ₹5L", subsidy: "Low interest",eligibility: "SHG women members in AP & TS",   link: "https://www.streenidhicredit.com/" },
    { id: 4, name: "NABARD SHG", fullName: "NABARD Self Help Group Bank Linkage",         ministry: "NABARD", amount: "₹50K–₹3L",  subsidy: "Subsidised",  eligibility: "SHG members with 6+ months savings", link: "https://www.nabard.org/" },
    { id: 5, name: "WE Hub",    fullName: "Women Entrepreneurs Hub — Telangana",          ministry: "Telangana", amount: "Incubation", subsidy: "Free support",eligibility: "Women entrepreneurs in Telangana",link: "https://wehub.telangana.gov.in/" },
  ],

  // ── COMMUNITY POSTS ───────────────────────────
  communityPosts: [
    { id: 1, author: "Priya S.",   avatar: "PS", time: "2h ago",  category: "question",  title: "Best packaging for pickles?",                  body: "I want to ship my gongura pickle across India. What type of airtight packaging works best and where to buy it cheaply?",  likes: 24, replies: 8  },
    { id: 2, author: "Rekha M.",   avatar: "RM", time: "5h ago",  category: "tip",       title: "How I got my first 100 customers on WhatsApp",  body: "Share your story in your status every day. Add a simple price list image. Ask every buyer to forward it to one friend. It works!",  likes: 67, replies: 15 },
    { id: 3, author: "Sunita K.",  avatar: "SK", time: "1d ago",  category: "success",   title: "First ₹10,000 month — thank you CMM!",          body: "Six months ago I had zero customers. Today I completed my first ₹10,000 month selling herbal face packs. Dreams do come true!", likes: 142, replies: 31 },
    { id: 4, author: "Meera J.",   avatar: "MJ", time: "2d ago",  category: "question",  title: "How to get GST registration for home business?", body: "My yearly sales crossed ₹20L this year. Do I need GST? How do I register and what documents do I need?",  likes: 18, replies: 12 },
    { id: 5, author: "Anitha R.",  avatar: "AR", time: "3d ago",  category: "tip",       title: "Reel ideas for handloom sellers",               body: "Show the full weaving process — from thread to finished saree. Behind-the-scenes content gets 3x more saves than product photos!",  likes: 89, replies: 22 },
    { id: 6, author: "Kavitha R.", avatar: "KR", time: "4d ago",  category: "success",   title: "Got featured in local newspaper!",              body: "A journalist found me through our CMM community page. The article brought 40 new customers in one week. Never underestimate PR!",  likes: 203, replies: 44 },
  ],

  // ── BUYERS (for dashboard) ────────────────────
  buyers: [
    { id: 1, name: "Divya Nair",      avatar: "DN", phone: "919876543001", productId: 1,  productName: "Silk Thread Bangles Set",     city: "Hyderabad",  time: "2h ago",  status: "Purchased",  repeat: true  },
    { id: 2, name: "Sravanthi K.",    avatar: "SK", phone: "919876543002", productId: 5,  productName: "Soy Wax Candle Set",          city: "Bengaluru",  time: "4h ago",  status: "Interested", repeat: false },
    { id: 3, name: "Mounika Reddy",   avatar: "MR", phone: "919876543003", productId: 9,  productName: "Dry Flower Resin Earrings",   city: "Chennai",    time: "6h ago",  status: "Contacted",  repeat: false },
    { id: 4, name: "Haritha Sharma",  avatar: "HS", phone: "919876543004", productId: 1,  productName: "Silk Thread Bangles Set",     city: "Vijayawada", time: "1d ago",  status: "Purchased",  repeat: true  },
    { id: 5, name: "Padmaja Rao",     avatar: "PR", phone: "919876543005", productId: 10, productName: "Festival Gift Hamper",        city: "Hyderabad",  time: "1d ago",  status: "Purchased",  repeat: false },
    { id: 6, name: "Swetha Laksmi",   avatar: "SL", phone: "919876543006", productId: 5,  productName: "Soy Wax Candle Set",          city: "Warangal",   time: "2d ago",  status: "Interested", repeat: false },
    { id: 7, name: "Bhavani Devi",    avatar: "BD", phone: "919876543007", productId: 9,  productName: "Dry Flower Resin Earrings",   city: "Guntur",     time: "3d ago",  status: "Purchased",  repeat: true  },
    { id: 8, name: "Usha Rani",       avatar: "UR", phone: "919876543008", productId: 3,  productName: "Terracotta Wall Hanging Set", city: "Vizag",      time: "4d ago",  status: "Contacted",  repeat: false },
  ],
};
