// =============================================
//  COMMUNITY MAKERS' MARKET — DATA STORE
// =============================================

const CMM_DATA = {

  // ── BUSINESS IDEAS ──────────────────────────
  businessIdeas: [
    { id: 1, title: "Homemade Pickles & Chutneys", category: "cooking", difficulty: "beginner", investment: "₹500–2,000", profit: "₹5,000–15,000/mo", demand: "high", icon: "🥫", desc: "Traditional recipes using local produce. Sell in local markets, online, or bulk orders for restaurants.", tags: ["food", "no-equipment", "women-friendly"] },
    { id: 2, title: "Handmade Jewellery", category: "jewelry", difficulty: "beginner", investment: "₹1,000–5,000", profit: "₹8,000–25,000/mo", demand: "high", icon: "💍", desc: "Beaded, wire-wrapped, or clay jewellery with unique designs. Huge demand on Instagram and local festivals.", tags: ["craft", "festive", "gifting"] },
    { id: 3, title: "Embroidery & Stitching", category: "tailoring", difficulty: "intermediate", investment: "₹2,000–8,000", profit: "₹10,000–30,000/mo", demand: "high", icon: "🧵", desc: "Custom embroidery on kurtis, dupattas, and home furnishings. Bridal season demand is very high.", tags: ["skilled", "seasonal", "bridal"] },
    { id: 4, title: "Clay & Terracotta Products", category: "crafting", difficulty: "beginner", investment: "₹1,500–4,000", profit: "₹6,000–18,000/mo", demand: "medium", icon: "🏺", desc: "Eco-friendly pots, décor, and idols. Growing demand for handmade sustainable products.", tags: ["eco", "sustainable", "festive"] },
    { id: 5, title: "Tiffin / Meal Delivery Service", category: "cooking", difficulty: "beginner", investment: "₹2,000–5,000", profit: "₹15,000–40,000/mo", demand: "very-high", icon: "🍱", desc: "Home-cooked meals for office workers and students. Subscription model ensures steady income.", tags: ["food", "daily-income", "women-friendly"] },
    { id: 6, title: "Handmade Candles & Soaps", category: "crafting", difficulty: "beginner", investment: "₹1,000–3,000", profit: "₹6,000–20,000/mo", demand: "high", icon: "🕯️", desc: "Scented soy candles and herbal soaps. Premium packaging increases perceived value and pricing.", tags: ["gifting", "wellness", "export-potential"] },
    { id: 7, title: "Traditional Rangoli & Kolam Art", category: "painting", difficulty: "beginner", investment: "₹500–2,000", profit: "₹5,000–12,000/mo", demand: "medium", icon: "🎨", desc: "Teach online classes or sell pre-made colour rangoli kits and stencils. Festive season peaks.", tags: ["cultural", "teaching", "seasonal"] },
    { id: 8, title: "Crochet & Knitting Products", category: "crafting", difficulty: "intermediate", investment: "₹2,000–5,000", profit: "₹8,000–22,000/mo", demand: "medium", icon: "🧶", desc: "Bags, baby clothes, décor items and winter wear. Very popular on Etsy and social media.", tags: ["craft", "export-potential", "gifting"] },
    { id: 9, title: "Digital Art & Illustration", category: "painting", difficulty: "intermediate", investment: "₹0–5,000", profit: "₹10,000–50,000/mo", demand: "high", icon: "🖥️", desc: "Custom portraits, wedding invitations, logo design for small businesses using free apps.", tags: ["digital", "students", "zero-inventory"] },
    { id: 10, title: "Silk Thread Jewellery", category: "jewelry", difficulty: "beginner", investment: "₹800–2,500", profit: "₹6,000–18,000/mo", demand: "high", icon: "🧿", desc: "Traditional South Indian silk thread bangles and earrings. Very popular for cultural events.", tags: ["cultural", "south-indian", "gifting"] },
    { id: 11, title: "Homemade Bakery & Sweets", category: "cooking", difficulty: "intermediate", investment: "₹3,000–10,000", profit: "₹12,000–35,000/mo", demand: "very-high", icon: "🎂", desc: "Cakes, cookies, ladoos, and festival sweets. Custom order cakes are premium-priced.", tags: ["food", "festive", "gifting"] },
    { id: 12, title: "Fabric Painting & Block Printing", category: "painting", difficulty: "intermediate", investment: "₹2,000–6,000", profit: "₹8,000–25,000/mo", demand: "medium", icon: "👘", desc: "Hand-painted sarees, kurtis and tote bags. Unique artistic pieces command high prices.", tags: ["art", "fashion", "export-potential"] },
    { id: 13, title: "Mehendi (Henna) Artist", category: "crafting", difficulty: "intermediate", investment: "₹500–2,000", profit: "₹10,000–30,000/mo", demand: "high", icon: "🌿", desc: "Bridal and festive mehendi services. Home visits and event bookings for consistent income.", tags: ["skilled", "bridal", "events"] },
    { id: 14, title: "Paper Craft & Origami Products", category: "crafting", difficulty: "beginner", investment: "₹500–1,500", profit: "₹4,000–12,000/mo", demand: "medium", icon: "📦", desc: "Gift boxes, greeting cards, and decorative items. Low investment, high creativity appeal.", tags: ["eco", "gifting", "zero-waste"] },
    { id: 15, title: "Handloom Weaving", category: "tailoring", difficulty: "advanced", investment: "₹10,000–30,000", profit: "₹20,000–60,000/mo", demand: "medium", icon: "🪢", desc: "Traditional handloom sarees and fabrics with GI tag potential. Premium market and export opportunities.", tags: ["traditional", "skilled", "export-potential"] },
    { id: 16, title: "YouTube / Instagram Content Creation", category: "digital", difficulty: "beginner", investment: "₹0–5,000", profit: "₹5,000–1,00,000/mo", demand: "very-high", icon: "📱", desc: "Share cooking recipes, craft tutorials, or lifestyle content. Ad revenue and brand deals.", tags: ["digital", "students", "women-friendly"] },
    { id: 17, title: "Tutoring & Online Classes", category: "digital", difficulty: "beginner", investment: "₹0–2,000", profit: "₹8,000–30,000/mo", demand: "very-high", icon: "📚", desc: "Teach academics, languages, yoga, cooking, or music online via Zoom or WhatsApp groups.", tags: ["education", "zero-inventory", "students"] },
    { id: 18, title: "Bag Making (Jute/Cloth)", category: "crafting", difficulty: "beginner", investment: "₹1,000–4,000", profit: "₹5,000–15,000/mo", demand: "high", icon: "👜", desc: "Eco-friendly jute and canvas bags. Corporates buy in bulk for branding; high repeat orders.", tags: ["eco", "bulk-orders", "sustainable"] },
    { id: 19, title: "Herbal Products & Organic Skincare", category: "cooking", difficulty: "intermediate", investment: "₹2,000–8,000", profit: "₹10,000–40,000/mo", demand: "very-high", icon: "🌱", desc: "Natural face packs, hair oils, and herbal powders. Growing organic beauty market in India.", tags: ["wellness", "women-friendly", "export-potential"] },
    { id: 20, title: "Puppet Making & Storytelling", category: "crafting", difficulty: "intermediate", investment: "₹1,000–5,000", profit: "₹5,000–15,000/mo", demand: "low", icon: "🎭", desc: "Traditional Tolu Bommalata puppets and educational storytelling kits for schools.", tags: ["cultural", "traditional", "education"] },
    { id: 21, title: "Photo Editing & Graphic Design", category: "digital", difficulty: "beginner", investment: "₹0–3,000", profit: "₹8,000–35,000/mo", demand: "very-high", icon: "🖌️", desc: "Edit photos for small businesses, weddings and social media using free tools like Canva.", tags: ["digital", "students", "zero-inventory"] },
    { id: 22, title: "Gift Hamper Curation", category: "crafting", difficulty: "beginner", investment: "₹2,000–6,000", profit: "₹8,000–25,000/mo", demand: "high", icon: "🎁", desc: "Curate and package premium gift hampers for festivals, weddings, and corporate events.", tags: ["gifting", "festive", "bulk-orders"] },
    { id: 23, title: "Macramé Wall Art & Decor", category: "crafting", difficulty: "intermediate", investment: "₹1,500–5,000", profit: "₹8,000–20,000/mo", demand: "medium", icon: "🪡", desc: "Trendy macramé wall hangings, plant hangers and table runners. Very popular for home décor.", tags: ["trending", "home-decor", "export-potential"] },
    { id: 24, title: "Pickled Vegetables & Fermented Foods", category: "cooking", difficulty: "beginner", investment: "₹1,000–3,000", profit: "₹6,000–18,000/mo", demand: "high", icon: "🥒", desc: "Mango pickle, gongura pachadi, and traditional fermented foods. Health-conscious market growing.", tags: ["food", "traditional", "health"] },
    { id: 25, title: "Handmade Diyas & Festive Decor", category: "crafting", difficulty: "beginner", investment: "₹500–2,000", profit: "₹5,000–30,000/mo", demand: "very-high", icon: "🪔", desc: "Painted clay diyas, torans, and festive decorations. Peak Diwali season business.", tags: ["festive", "seasonal", "cultural"] },
    { id: 26, title: "Tanjore Painting", category: "painting", difficulty: "advanced", investment: "₹5,000–15,000", profit: "₹15,000–50,000/mo", demand: "medium", icon: "🖼️", desc: "Traditional Tanjore-style paintings with gold leaf. Premium art for collectors and gifts.", tags: ["traditional", "premium", "cultural"] },
    { id: 27, title: "Dry Flower & Resin Art", category: "crafting", difficulty: "intermediate", investment: "₹2,000–6,000", profit: "₹8,000–22,000/mo", demand: "high", icon: "🌸", desc: "Resin-preserved flowers in jewellery and décor frames. Trendy and very Instagram-worthy.", tags: ["trending", "gifting", "export-potential"] },
    { id: 28, title: "Namkeen & Snacks Production", category: "cooking", difficulty: "beginner", investment: "₹2,000–8,000", profit: "₹10,000–30,000/mo", demand: "very-high", icon: "🥜", desc: "Traditional South Indian snacks like murukku, chivda, and mixture. Great for wholesale.", tags: ["food", "bulk-orders", "traditional"] },
  ],

  // ── MARKETPLACE PRODUCTS ────────────────────
  products: [
    {
      id: 1,
      name: "Handmade Silk Thread Bangles Set",
      seller: "Lakshmi Crafts",
      sellerPhone: "919876543210",
      price: 350,
      originalPrice: 500,
      category: "jewelry",
      rating: 4.8,
      reviews: 124,
      image: null,
      emoji: "💛",
      tags: ["silk", "traditional", "set-of-12"],
      desc: "Beautiful handcrafted silk thread bangles in vibrant colours. Set of 12 bangles. Perfect for festivals and weddings.",
      location: "Hyderabad",
      inStock: true,
    },
    {
      id: 2,
      name: "Gongura Pickle — 500g",
      seller: "Amma's Kitchen",
      sellerPhone: "919845321076",
      price: 180,
      originalPrice: 220,
      category: "food",
      rating: 4.9,
      reviews: 256,
      image: null,
      emoji: "🥫",
      tags: ["organic", "spicy", "andhra-special"],
      desc: "Authentic Andhra-style gongura pachadi made with fresh sorrel leaves. No preservatives. Family recipe passed down 3 generations.",
      location: "Vijayawada",
      inStock: true,
    },
    {
      id: 3,
      name: "Terracotta Wall Hanging Set",
      seller: "Mitti Arts",
      sellerPhone: "919765432100",
      price: 650,
      originalPrice: 900,
      category: "home-decor",
      rating: 4.7,
      reviews: 89,
      image: null,
      emoji: "🏺",
      tags: ["eco", "handmade", "terracotta"],
      desc: "Set of 3 terracotta wall hanging pieces. Each piece is hand-shaped and painted by artisans. Adds a rustic charm to your home.",
      location: "Nizamabad",
      inStock: true,
    },
    {
      id: 4,
      name: "Custom Macramé Wall Art",
      seller: "Thread & Soul",
      sellerPhone: "919988776655",
      price: 1200,
      originalPrice: 1600,
      category: "home-decor",
      rating: 4.6,
      reviews: 67,
      image: null,
      emoji: "🪡",
      tags: ["custom", "boho", "wall-decor"],
      desc: "Handwoven macramé wall hanging — 24×36 inches. Custom size and colour available. Ships in 5–7 days.",
      location: "Warangal",
      inStock: true,
    },
    {
      id: 5,
      name: "Herbal Face Pack Kit",
      seller: "NaturVeda",
      sellerPhone: "919554321987",
      price: 299,
      originalPrice: 450,
      category: "beauty",
      rating: 4.8,
      reviews: 312,
      image: null,
      emoji: "🌿",
      tags: ["organic", "chemical-free", "gift-set"],
      desc: "100% natural face pack with turmeric, neem, and sandalwood. Brightens skin tone. Suitable for all skin types.",
      location: "Guntur",
      inStock: true,
    },
    {
      id: 6,
      name: "Handpainted Fabric Tote Bag",
      seller: "Canvas Studio",
      sellerPhone: "919432156789",
      price: 450,
      originalPrice: 600,
      category: "fashion",
      rating: 4.5,
      reviews: 78,
      image: null,
      emoji: "👜",
      tags: ["eco", "handpainted", "unique"],
      desc: "Hand-painted canvas tote bag with traditional motifs. Each bag is unique — no two are the same. Water-resistant lining.",
      location: "Tirupati",
      inStock: true,
    },
    {
      id: 7,
      name: "Dry Flower Resin Earrings",
      seller: "Petal & Resin",
      sellerPhone: "919867452310",
      price: 280,
      originalPrice: 380,
      category: "jewelry",
      rating: 4.9,
      reviews: 145,
      image: null,
      emoji: "🌸",
      tags: ["trendy", "resin", "floral"],
      desc: "Delicate earrings with real preserved flowers in clear resin. Lightweight. Available in rose, lavender, and marigold designs.",
      location: "Vizag",
      inStock: true,
    },
    {
      id: 8,
      name: "Andhra Murukku — 400g Pack",
      seller: "Grandma's Snacks",
      sellerPhone: "919776543219",
      price: 150,
      originalPrice: 180,
      category: "food",
      rating: 4.7,
      reviews: 189,
      image: null,
      emoji: "🥨",
      tags: ["traditional", "crispy", "rice-flour"],
      desc: "Crispy, freshly made murukku in traditional Andhra style. Made with rice flour and sesame. Great for snacking or gifting.",
      location: "Kurnool",
      inStock: true,
    },
    {
      id: 9,
      name: "Handmade Soy Wax Candle Set",
      seller: "Glow & Co",
      sellerPhone: "919654321876",
      price: 520,
      originalPrice: 700,
      category: "home-decor",
      rating: 4.8,
      reviews: 92,
      image: null,
      emoji: "🕯️",
      tags: ["soy", "scented", "gift-set"],
      desc: "Set of 4 soy wax candles — jasmine, sandalwood, rose, and vanilla. 35+ hours burn time each. Cotton wick.",
      location: "Hyderabad",
      inStock: true,
    },
    {
      id: 10,
      name: "Tanjore Painting — Lord Ganesha",
      seller: "Divine Art Gallery",
      sellerPhone: "919543218765",
      price: 3500,
      originalPrice: 4500,
      category: "art",
      rating: 4.9,
      reviews: 34,
      image: null,
      emoji: "🖼️",
      tags: ["premium", "traditional", "gold-leaf"],
      desc: "Authentic Tanjore painting with 22K gold leaf work. 12×16 inch framed. Certificate of authenticity included.",
      location: "Vijayawada",
      inStock: true,
    },
    {
      id: 11,
      name: "Crochet Baby Booties & Hat Set",
      seller: "Wooly Wonders",
      sellerPhone: "919432187654",
      price: 399,
      originalPrice: 550,
      category: "fashion",
      rating: 4.7,
      reviews: 118,
      image: null,
      emoji: "🧶",
      tags: ["baby", "handmade", "gift"],
      desc: "Adorable hand-crocheted baby set with booties and matching hat. Available in pink, blue, and yellow. Newborn to 6 months.",
      location: "Nellore",
      inStock: true,
    },
    {
      id: 12,
      name: "Festival Gift Hamper",
      seller: "Curated with Love",
      sellerPhone: "919876123456",
      price: 1800,
      originalPrice: 2500,
      category: "gifting",
      rating: 4.8,
      reviews: 56,
      image: null,
      emoji: "🎁",
      tags: ["corporate", "festive", "bulk-available"],
      desc: "Premium gift hamper with pickle, dry fruits, candle, and handmade chocolates. Custom branding available for 50+ orders.",
      location: "Hyderabad",
      inStock: true,
    },
  ],

  // ── SUCCESS STORIES ─────────────────────────
  stories: [
    {
      id: 1,
      name: "Padma Reddy",
      age: 35,
      location: "Vijayawada",
      business: "Homemade Pickle Brand",
      income: "₹45,000/month",
      emoji: "🥫",
      tag: "From Kitchen to Market",
      story: "Three years ago, Padma was a homemaker with a talent for making traditional Andhra pickles. With no business experience, she started selling to neighbours. After joining a self-help group and using digital platforms, her pickle brand now ships across India.",
      challenge: "No money for marketing, no knowledge of packaging.",
      solution: "Learned branding basics, reinvested profits into better packaging.",
      quote: "My kitchen became my factory. My WhatsApp group became my shop.",
    },
    {
      id: 2,
      name: "Arjun Venkat",
      age: 21,
      location: "Hyderabad",
      business: "Digital Art & Custom Portraits",
      income: "₹30,000/month",
      emoji: "🎨",
      tag: "Art Pays Off",
      story: "Engineering student Arjun started doing digital illustrations in his hostel room using a second-hand tablet. He began taking custom portrait orders on Instagram. Within 8 months, his art income exceeded his part-time tutoring income.",
      challenge: "Underpricing his work and not knowing how to find clients.",
      solution: "Raised prices after building a portfolio; used Instagram Reels for visibility.",
      quote: "My art degree paid off before I even graduated.",
    },
    {
      id: 3,
      name: "Meena Kumari",
      age: 42,
      location: "Warangal",
      business: "Handloom Sarees",
      income: "₹65,000/month",
      emoji: "🪢",
      tag: "Weaving Dreams",
      story: "Meena learned weaving from her mother but had no market beyond local fairs. A district-level women's entrepreneurship program helped her get a Mudra loan and set up an online presence. Her heritage handloom sarees now have buyers in the USA and UK.",
      challenge: "Traditional craft with very limited modern market reach.",
      solution: "Got GI tag certification; partnered with export-focused NGO.",
      quote: "Every thread I weave carries my family's legacy and my children's future.",
    },
    {
      id: 4,
      name: "Sunita Devi",
      age: 29,
      location: "Nellore",
      business: "Tiffin Delivery Service",
      income: "₹35,000/month",
      emoji: "🍱",
      tag: "Feeding Futures",
      story: "When her husband lost his job, Sunita started cooking tiffins for 5 office workers. Through word of mouth and a simple WhatsApp group, she grew to 60 daily customers in under a year. She now employs 2 helpers.",
      challenge: "Managing delivery logistics and quality consistency at scale.",
      solution: "Fixed menu rotation, hired a helper, and used a simple Excel for orders.",
      quote: "I never imagined my cooking could feed my family's dreams too.",
    },
  ],

  // ── GOVERNMENT SCHEMES ──────────────────────
  schemes: [
    {
      id: 1,
      name: "PM MUDRA Loan",
      icon: "🏦",
      tag: "Loan Scheme",
      maxAmount: "₹10 Lakhs",
      eligibility: "Any Indian citizen starting a micro or small business",
      benefits: ["No collateral required up to ₹10L", "Low interest rates", "3 tiers: Shishu (₹50K), Kishore (₹5L), Tarun (₹10L)", "Direct bank disbursement"],
      steps: ["Visit nearest bank/MFI or pmmy.gov.in", "Fill MUDRA loan application form", "Submit Aadhaar, PAN, and business plan", "Bank appraises and disburses within 7–30 days"],
      link: "https://www.mudra.org.in",
    },
    {
      id: 2,
      name: "Self-Help Group (SHG) Registration",
      icon: "👥",
      tag: "Community Support",
      maxAmount: "Group savings + bank linkage",
      eligibility: "Women in a group of 10–20 members",
      benefits: ["Access to group savings and credit", "Government bank linkage programs", "Priority for government scheme benefits", "Skill training and capacity building"],
      steps: ["Form a group of 10–20 women", "Open group savings account at bank", "Maintain regular meetings and savings record", "Apply for SHG linkage at district rural development office"],
      link: "https://nrlm.gov.in",
    },
    {
      id: 3,
      name: "Udyam Registration (MSME)",
      icon: "📋",
      tag: "Business Registration",
      maxAmount: "Free registration",
      eligibility: "Any micro, small, or medium enterprise",
      benefits: ["Official MSME certificate", "Priority sector lending from banks", "Government tender preferences", "Subsidies on patent registration and ISO certification"],
      steps: ["Go to udyamregistration.gov.in", "Enter Aadhaar and PAN details", "Fill business details (no documents required)", "Get Udyam Registration Number instantly"],
      link: "https://udyamregistration.gov.in",
    },
    {
      id: 4,
      name: "Mahila Udyam Nidhi Scheme",
      icon: "👩‍💼",
      tag: "Women Entrepreneur",
      maxAmount: "₹10 Lakhs",
      eligibility: "Women entrepreneurs in small-scale industries",
      benefits: ["Soft loan at subsidised interest", "5-year repayment period", "No collateral for loans up to ₹10L", "Special support for SC/ST women"],
      steps: ["Apply through SIDBI or State Finance Corporation", "Submit business plan and ID proof", "Interview with loan officer", "Disbursement within 30 days of approval"],
      link: "https://www.sidbi.in",
    },
    {
      id: 5,
      name: "PM Vishwakarma Scheme",
      icon: "🔨",
      tag: "Skill & Craft",
      maxAmount: "₹3 Lakhs + ₹15,000 toolkit",
      eligibility: "Traditional artisans and craftspeople (18 trades)",
      benefits: ["Free skill training with ₹500/day stipend", "₹15,000 toolkit support", "Collateral-free credit up to ₹3L", "PM Vishwakarma certificate and ID card"],
      steps: ["Register on pmvishwakarma.gov.in via CSC", "Verify trade at gram panchayat level", "Complete 5-day basic + 15-day advanced training", "Apply for credit and toolkit grant"],
      link: "https://pmvishwakarma.gov.in",
    },
    {
      id: 6,
      name: "Skill India / PMKVY",
      icon: "🎓",
      tag: "Free Skill Training",
      maxAmount: "Free training + certificate",
      eligibility: "Any Indian aged 15–45 years",
      benefits: ["Free certified skill training", "Monetary reward on certification", "Job placement support", "1,000+ skill courses available"],
      steps: ["Register at skillindia.gov.in", "Choose a skill course near you", "Complete training at empanelled centre", "Appear for assessment and get NSQF certificate"],
      link: "https://skillindia.gov.in",
    },
  ],

  // ── COMMUNITY POSTS ─────────────────────────
  communityPosts: [
    { id: 1, category: "marketing", author: "Priya S.", avatar: "P", time: "2 hours ago", title: "How do I price my handmade jewellery?", replies: 18, likes: 34, tag: "question" },
    { id: 2, category: "finance", author: "Ravi K.", avatar: "R", time: "5 hours ago", title: "Got my Mudra loan approved! Here's what helped.", replies: 42, likes: 89, tag: "success" },
    { id: 3, category: "marketing", author: "Anitha M.", avatar: "A", time: "1 day ago", title: "Instagram vs WhatsApp — which works better for selling locally?", replies: 31, likes: 56, tag: "discussion" },
    { id: 4, category: "operations", author: "Suresh T.", avatar: "S", time: "1 day ago", title: "Best packaging suppliers in Hyderabad for under ₹5 per unit", replies: 24, likes: 45, tag: "tip" },
    { id: 5, category: "legal", author: "Meena D.", avatar: "M", time: "2 days ago", title: "Do I need FSSAI license for homemade pickles?", replies: 16, likes: 27, tag: "question" },
    { id: 6, category: "marketing", author: "Kavitha R.", avatar: "K", time: "3 days ago", title: "Went from 0 to 200 customers in 6 months — my story", replies: 58, likes: 143, tag: "success" },
    { id: 7, category: "finance", author: "Naresh P.", avatar: "N", time: "3 days ago", title: "How to open a current account for your micro business?", replies: 12, likes: 34, tag: "guide" },
    { id: 8, category: "operations", author: "Sita V.", avatar: "S", time: "4 days ago", title: "Managing home-based business while taking care of kids — tips?", replies: 27, likes: 71, tag: "discussion" },
  ],

  // ── LEARNING MODULES ────────────────────────
  modules: [
    {
      id: 1, title: "Business Planning & Feasibility", icon: "📊", lessonCount: 8, duration: "3 hours", level: "beginner",
      desc: "Learn to validate your business idea, do market research, and create your first business plan.",
      topics: ["Idea validation", "Market sizing", "Competitor analysis", "Basic business plan writing"],
      lessons: [
        { id: "1-1", title: "What Makes a Good Business Idea?", duration: "18 min", content: "A good business idea solves a real problem or fulfils a clear need. Ask yourself: Does someone need this? Can I make money from it? Do I have the skills?\n\n✅ Key points:\n• Identify a pain point in your community\n• Check if people will pay for it\n• Assess your own skills and resources\n• Start small — test before scaling\n\n📝 Action: Write down 3 business ideas you could start with skills you already have." },
        { id: "1-2", title: "How to Validate Your Idea", duration: "22 min", content: "Validation means checking if real people want and will pay for your product BEFORE you invest money.\n\n✅ Steps to validate:\n1. Tell 10 people about your idea and watch their reaction\n2. Ask if they would pay ₹X for it\n3. Try pre-selling — collect ₹100 advance from 5 customers\n4. Make a small batch and sell it first\n\n💡 If 3 out of 10 people say yes and show real interest, you have a viable idea!" },
        { id: "1-3", title: "Market Research Basics", duration: "25 min", content: "Market research helps you understand WHO your customers are and HOW MANY potential buyers exist.\n\n✅ Simple market research steps:\n• Visit local markets and observe what sells\n• Check Facebook/Instagram for similar businesses\n• Ask friends and family for honest feedback\n• Look at competitor pricing\n\n📊 Key questions to answer:\n1. Who is my target customer? (age, location, income)\n2. How much will they pay?\n3. How often will they buy?" },
        { id: "1-4", title: "Understanding Your Competition", duration: "20 min", content: "Knowing your competitors helps you differentiate your product and find gaps in the market.\n\n✅ How to analyse competitors:\n• Search for similar products on WhatsApp groups and Instagram\n• Visit local markets and note pricing\n• Identify what they do well and what they miss\n\n🎯 Your Competitive Advantage could be:\n• Better quality or ingredients\n• Faster delivery\n• More personal service\n• Traditional/authentic recipes\n• Unique packaging" },
        { id: "1-5", title: "Your First Business Plan", duration: "30 min", content: "A business plan doesn't need to be fancy — even a 1-page plan is enough to start.\n\n📄 Simple 1-Page Business Plan:\n\n1. WHAT I SELL: [Product/Service name]\n2. WHO I SELL TO: [Target customer description]\n3. HOW I REACH THEM: [WhatsApp, Instagram, local market]\n4. WHAT IT COSTS ME: [Raw materials + time]\n5. WHAT I CHARGE: [Selling price]\n6. MY PROFIT PER UNIT: [Price - Cost]\n7. HOW MANY I NEED TO SELL: [Monthly target]\n8. HOW I'LL GROW: [First 3 months plan]\n\n📥 Download the free Business Plan Template from the Resources section." },
        { id: "1-6", title: "Calculating Break-Even Point", duration: "18 min", content: "Break-even is the point where your income equals your expenses — you're not losing money.\n\n📊 Formula:\nBreak-Even Units = Fixed Costs ÷ (Selling Price - Variable Cost per unit)\n\n💡 Example:\n• Fixed costs (rent, tools): ₹2,000/month\n• Selling price per pickle jar: ₹150\n• Cost of ingredients per jar: ₹60\n• Profit per jar: ₹90\n• Break-even: 2,000 ÷ 90 = 23 jars/month\n\nSell more than 23 jars → You make profit! ✅" },
        { id: "1-7", title: "Setting SMART Business Goals", duration: "15 min", content: "SMART goals keep you focused and motivated.\n\nSMART = Specific, Measurable, Achievable, Relevant, Time-bound\n\n✅ Example of a SMART goal:\n❌ Bad: 'I want to earn more money'\n✅ Good: 'I will sell 50 jars of pickle per month by August 2026 and earn ₹4,500 net profit'\n\n🎯 Set 3 goals:\n1. First 30 days goal\n2. First 3 months goal\n3. First year goal\n\nWrite them down and review every week!" },
        { id: "1-8", title: "Module Quiz & Review", duration: "12 min", content: "🎉 Congratulations! You've completed Module 1.\n\n📝 Quick Review Quiz:\n\n1. What are the 3 questions to ask when validating a business idea?\n2. What is a break-even point?\n3. What does SMART stand for in goal-setting?\n4. Name 2 ways to do simple market research without spending money.\n\n✅ Check your answers:\n1. Does someone need this? Will they pay? Do I have the skills?\n2. The point where income = expenses (no profit or loss)\n3. Specific, Measurable, Achievable, Relevant, Time-bound\n4. Ask friends/family, observe local markets, check social media\n\n🚀 Next: Start Module 2 — Legal & Regulatory Setup!" },
      ]
    },
    {
      id: 2, title: "Legal & Regulatory Setup", icon: "⚖️", lessonCount: 6, duration: "2.5 hours", level: "beginner",
      desc: "Understand licenses, registrations, and legal requirements for running a small business in India.",
      topics: ["Udyam registration", "FSSAI for food businesses", "GST basics", "Shop & Establishment Act"],
      lessons: [
        { id: "2-1", title: "Do I Need to Register My Business?", duration: "15 min", content: "Not every small business needs registration, but it helps!\n\n✅ Benefits of registration:\n• Build trust with customers\n• Open a business bank account\n• Access government schemes and loans\n• Legal protection\n\n📋 Common registrations for small businesses:\n1. Udyam Registration (MSME) — FREE, highly recommended\n2. FSSAI — Required for food businesses\n3. GST — Required only if turnover > ₹40 Lakhs/year\n4. Shop & Establishment — Required if you have a physical shop\n\n💡 Start with Udyam Registration — it's free and takes 10 minutes!" },
        { id: "2-2", title: "Udyam Registration — Step by Step", duration: "25 min", content: "Udyam Registration gives you official MSME status and is completely FREE.\n\n📋 How to register:\n1. Go to udyamregistration.gov.in\n2. Click 'For New Entrepreneurs'\n3. Enter your Aadhaar number\n4. Enter OTP sent to your phone\n5. Fill in your business details:\n   • Business name\n   • Type of business\n   • Location\n   • Main activity (manufacturing/service)\n6. Submit — You get your Udyam Registration Number instantly!\n\n✅ Benefits you get:\n• Priority bank loans\n• Government tender eligibility\n• Subsidies on certifications\n• Protection from delayed payments" },
        { id: "2-3", title: "FSSAI License for Food Businesses", duration: "20 min", content: "If you sell food products, FSSAI registration is mandatory.\n\n📋 Types of FSSAI:\n• Basic Registration: Annual turnover < ₹12 Lakhs — FREE\n• State License: Turnover ₹12L to ₹20Cr — ₹2,000/year\n• Central License: Large-scale manufacturing\n\n✅ How to register (Basic):\n1. Go to foscos.fssai.gov.in\n2. Create an account\n3. Apply for 'Basic Registration'\n4. Fill business details and pay fee\n5. Get your 14-digit FSSAI number in 7–30 days\n6. Print on all your packaging!\n\n⚠️ Important: Display your FSSAI number on all food products you sell." },
        { id: "2-4", title: "GST Basics — When Do You Need It?", duration: "22 min", content: "GST (Goods & Services Tax) registration is needed only when your annual turnover crosses ₹40 Lakhs (or ₹20L for services).\n\n✅ As a small home-based seller:\n• If you earn < ₹40 Lakhs/year → No GST needed\n• You can still sell freely without GST\n• Some B2B buyers may ask for GSTIN — register if needed\n\n📋 If you need to register:\n1. Go to gst.gov.in\n2. Apply for new registration\n3. Submit: PAN, Aadhaar, bank account, address proof\n4. Get GSTIN in 3–7 working days\n\n💡 Tip: Consult a local CA for GST filing — costs ₹500-1,000/month and saves headaches!" },
        { id: "2-5", title: "Shop & Establishment Act", duration: "18 min", content: "The Shop & Establishment Act applies if you have a physical shop or employ workers.\n\n✅ Who needs it:\n• Shops open to the public\n• Businesses with employees\n• Offices and warehouses\n\n❌ Who doesn't need it:\n• Pure home-based businesses with no shop\n• Online-only sellers\n• Sole proprietors working alone from home\n\n📋 How to register:\n1. Visit your local municipal corporation\n2. Submit: ID proof, address proof, business details\n3. Pay the fee (varies by state: ₹200-1,000)\n4. Get your registration certificate\n\n⏰ Validity: Usually 1-5 years, needs renewal." },
        { id: "2-6", title: "Module Quiz & Review", duration: "10 min", content: "🎉 Module 2 Complete!\n\n📝 Quiz:\n1. Which registration is FREE and gives MSME status?\n2. What is the turnover limit for Basic FSSAI registration?\n3. When do you MUST register for GST?\n4. Do home-based businesses need Shop & Establishment registration?\n\n✅ Answers:\n1. Udyam Registration\n2. Less than ₹12 Lakhs per year\n3. When annual turnover crosses ₹40 Lakhs (goods) or ₹20 Lakhs (services)\n4. Usually NO — only if you have a physical shop or employees\n\n🚀 Next: Module 3 — Financial Management!" },
      ]
    },
    {
      id: 3, title: "Financial Management", icon: "💰", lessonCount: 10, duration: "4 hours", level: "intermediate",
      desc: "Learn to manage money, keep records, and make your business profitable from day one.",
      topics: ["Profit & loss basics", "Pricing strategy", "Bookkeeping with free tools", "Managing cash flow"],
      lessons: [
        { id: "3-1", title: "Understanding Profit & Loss", duration: "20 min", content: "Profit = Revenue - All Costs\n\n📊 Two types of costs:\n• Fixed Costs: Same every month (rent, tools, equipment)\n• Variable Costs: Change with sales (raw materials, packaging, delivery)\n\n💡 Example — Pickle Business:\n• Revenue: 50 jars × ₹150 = ₹7,500\n• Variable costs: 50 × ₹60 = ₹3,000\n• Fixed costs: ₹1,000 (gas, jars, labels)\n• NET PROFIT = ₹7,500 - ₹3,000 - ₹1,000 = ₹3,500\n\n✅ Track this every month to understand if your business is growing!" },
        { id: "3-2", title: "How to Price Your Products", duration: "25 min", content: "Pricing is one of the most important business decisions.\n\n📋 The Cost-Plus Pricing Formula:\nSelling Price = (Material Cost + Labour Cost + Overhead) × (1 + Profit Margin%)\n\n💡 Example:\n• Materials: ₹60\n• Your time (2 hrs × ₹25): ₹50\n• Overhead (10%): ₹11\n• Total Cost: ₹121\n• Add 40% profit margin: ₹121 × 1.4 = ₹169\n• Sell at ₹175 (round up)\n\n⚠️ Common mistake: Never price below your total cost!\n\n📥 Download the free Pricing Calculator from Resources." },
        { id: "3-3", title: "Simple Bookkeeping with Free Tools", duration: "22 min", content: "You don't need expensive software to keep books.\n\n✅ Free tools that work:\n• Google Sheets (free, works on phone)\n• Khatabook app (free, in Telugu)\n• OkCredit app (free, for tracking credit/debit)\n• Paper register — simple and reliable\n\n📋 What to record daily:\n1. Date\n2. Income received (from whom, for what)\n3. Expenses paid (to whom, for what)\n4. Running balance\n\n💡 Golden Rule: Record every transaction the same day. Even ₹10 matters!\n\n📥 Download the free Bookkeeping Template from Resources." },
        { id: "3-4", title: "Managing Cash Flow", duration: "20 min", content: "Cash flow = Money coming IN vs money going OUT.\n\nEven a profitable business can fail if cash isn't managed well!\n\n✅ Tips to manage cash flow:\n• Collect payment BEFORE delivery when possible\n• Give credit only to trusted customers\n• Keep 1 month of expenses as emergency reserve\n• Buy raw materials in bulk for discounts\n• Negotiate 15-30 day payment terms with suppliers\n\n⚠️ Warning signs of poor cash flow:\n• Unable to pay for raw materials\n• Delaying orders due to lack of stock\n• Borrowing money for daily expenses\n\n💡 Solution: Require 50% advance payment on all custom orders!" },
        { id: "3-5", title: "Taxes for Small Businesses", duration: "18 min", content: "As a small home-based business, your tax obligations are minimal.\n\n📋 Key taxes to know:\n• Income Tax: Pay only if annual income > ₹3 Lakhs (basic exemption)\n• GST: Only if turnover > ₹40 Lakhs\n• Presumptive Taxation (Section 44AD): If income < ₹2Cr, pay tax on 6-8% of turnover\n\n✅ Best practices:\n• File ITR every year (even if no tax due)\n• Keep all receipts and invoices\n• Use a CA for filing — costs ₹500-2,000 per year\n• Separate personal and business expenses\n\n💡 Filing ITR builds your credit score and helps you get loans!" },
        { id: "3-6", title: "Saving & Reinvesting Profits", duration: "15 min", content: "How you use your profits determines how fast you grow.\n\n📋 The 50-30-20 Rule for small businesses:\n• 50% → Business expenses and raw materials\n• 30% → Your personal income\n• 20% → Business savings / reinvestment\n\n✅ What to reinvest in:\n• Better equipment (saves time = more production)\n• Improved packaging (higher perceived value)\n• Marketing (more customers = more sales)\n• Training (learn new skills)\n\n💰 Open a separate savings account for your business. Never mix personal and business money!" },
        { id: "3-7", title: "Getting a Business Loan", duration: "22 min", content: "When your business needs capital to grow, here's how to get a loan.\n\n📋 Options for small businesses:\n1. MUDRA Loan: Up to ₹10 Lakhs, no collateral — BEST for beginners\n2. SHG Bank Linkage: Through your Self-Help Group\n3. PM Vishwakarma: Up to ₹3 Lakhs for artisans\n4. MSME Business Loan: From banks after 1-2 years of business\n\n✅ What banks look for:\n• Income proof (bank statements, ITR)\n• Udyam Registration\n• Business plan\n• Credit history\n\n💡 Start with MUDRA — it's designed for first-time entrepreneurs!" },
        { id: "3-8", title: "Reading Your Finances", duration: "18 min", content: "Three numbers every business owner must know monthly:\n\n1. 📈 GROSS REVENUE: Total money collected from sales\n\n2. 💸 TOTAL EXPENSES: Everything spent (materials, packaging, transport, tools)\n\n3. 💰 NET PROFIT: Revenue - Expenses\n\n✅ Monthly check-up questions:\n• Is my revenue growing month-on-month?\n• Is my profit margin stable or improving?\n• Are any costs growing too fast?\n• Can I afford to invest in growth this month?\n\n📊 Track these 3 numbers every month and you'll always know how your business is doing!" },
        { id: "3-9", title: "Common Financial Mistakes", duration: "15 min", content: "Learn from others' mistakes so you don't make them!\n\n❌ Top 10 mistakes home business owners make:\n1. Not separating personal and business money\n2. Underpricing products\n3. Giving too much credit to customers\n4. Not recording daily transactions\n5. Spending profits before saving\n6. No emergency fund\n7. Buying in small quantities (costs more)\n8. Not charging for delivery\n9. Ignoring slow-moving inventory\n10. Not raising prices when costs increase\n\n✅ Fix: Address even ONE of these mistakes this week. It will directly improve your profits!" },
        { id: "3-10", title: "Module Quiz & Review", duration: "12 min", content: "🎉 Module 3 Complete — You're a Financial Champion!\n\n📝 Quiz:\n1. What is the formula for Net Profit?\n2. Name the free bookkeeping app that works in Telugu.\n3. What is the 50-30-20 rule?\n4. What is the best loan scheme for first-time entrepreneurs?\n\n✅ Answers:\n1. Net Profit = Revenue - All Expenses\n2. Khatabook (also OkCredit)\n3. 50% business expenses, 30% personal income, 20% savings/reinvestment\n4. MUDRA Loan (no collateral, up to ₹10 Lakhs)\n\n🚀 Next: Module 4 — Marketing & Sales!" },
      ]
    },
    {
      id: 4, title: "Marketing & Sales", icon: "📢", lessonCount: 12, duration: "5 hours", level: "beginner",
      desc: "Attract customers and grow your sales using social media, WhatsApp, and word-of-mouth.",
      topics: ["WhatsApp Business setup", "Instagram for business", "Product photography tips", "Building customer loyalty"],
      lessons: [
        { id: "4-1", title: "Know Your Customer", duration: "18 min", content: "Marketing works only when you know WHO you're talking to.\n\n📋 Define your ideal customer:\n• Age range\n• Location (local, nearby city, or online)\n• Income level\n• What problem are they solving by buying from you?\n• Where do they spend time online?\n\n💡 Example — Pickle seller:\n• Women aged 25-50\n• Working professionals who miss home food\n• Located in cities far from Andhra\n• Active on WhatsApp and Facebook\n\n✅ Action: Write a description of your 'dream customer' in 5 sentences." },
        { id: "4-2", title: "Setting Up WhatsApp Business", duration: "22 min", content: "WhatsApp Business is the #1 tool for local selling — FREE and extremely powerful.\n\n📱 Setup steps:\n1. Download 'WhatsApp Business' app\n2. Enter your business phone number\n3. Set up Business Profile:\n   • Business name and logo\n   • Category (Food/Retail/Services)\n   • Description\n   • Address and hours\n4. Create a Product Catalog with photos and prices\n5. Set Auto-Reply message for off-hours\n6. Set Greeting Message for new contacts\n\n✅ Features to use:\n• Broadcast Lists: Send updates to 256 contacts at once\n• Labels: Organise customers (New, Regular, Paid, Pending)\n• Quick Replies: Save common responses" },
        { id: "4-3", title: "Instagram for Your Business", duration: "25 min", content: "Instagram can bring you customers from across India and beyond!\n\n📸 Setup:\n1. Create a Business Account (free)\n2. Username: Keep it simple @YourBusinessName\n3. Bio: What you sell + location + WhatsApp link\n4. Profile photo: Your logo or a clear product photo\n\n✅ Content strategy:\n• Post 3-4 times per week\n• Mix: Product photos (50%), Behind-the-scenes (30%), Tips/Stories (20%)\n• Use Reels for maximum reach — even 15-second videos work!\n• Use 5-10 relevant hashtags\n\n🎯 Best hashtags for Telugu sellers:\n#AndhraHomemade #TeluguBusiness #MadeInAndhra #HandmadeIndia #LocalMaker" },
        { id: "4-4", title: "Product Photography on Your Phone", duration: "20 min", content: "Great photos sell products — and you don't need a camera!\n\n📸 Phone photography tips:\n\n✅ Lighting:\n• Always shoot near a window in natural light\n• Avoid harsh direct sunlight — use diffused light\n• Shoot in the morning (10am-12pm) for best light\n\n✅ Background:\n• Use plain white or pastel cloth as background\n• A ₹50 chart paper works perfectly\n• Remove clutter from the frame\n\n✅ Composition:\n• Clean your phone camera lens first!\n• Shoot from above (flat lay) for food products\n• Try multiple angles — pick the best 3\n• Free editing: Snapseed app (free)\n\n💡 Before vs After: Edit every photo before posting. Brightness +10, Contrast +5, Sharpness +3." },
        { id: "4-5", title: "Writing Product Descriptions That Sell", duration: "18 min", content: "Your description should make the customer feel they NEED to buy right now.\n\n📝 Formula: AIDA\n• A — Attention: Start with the benefit, not the feature\n• I — Interest: Describe what makes it special\n• D — Desire: Create emotional connection\n• A — Action: Clear CTA (WhatsApp number)\n\n💡 Example — Gongura Pickle:\n❌ Bad: 'Gongura pickle 500g, made at home'\n✅ Good: 'Craving authentic Andhra flavour far from home? 🥫 Our Gongura Pachadi is made with fresh sorrel leaves — no preservatives, no shortcuts. Same recipe your grandma would approve. Order via WhatsApp 👇'\n\n✅ Always include: Weight, ingredients, shelf life, price, and your WhatsApp number!" },
        { id: "4-6", title: "Pricing Strategies That Attract Buyers", duration: "18 min", content: "Pricing is marketing too. Here's how to use it strategically.\n\n📋 Pricing strategies:\n\n1. Bundle Pricing: '3 jars for ₹400 (save ₹50)' — increases average order value\n\n2. Anchor Pricing: Show original price crossed out: ~~₹500~~ ₹350 — creates perceived value\n\n3. Psychological Pricing: ₹199 feels much cheaper than ₹200\n\n4. Premium Pricing: Higher price = higher perceived quality (for artisan products)\n\n5. Loss Leader: Sell one product cheap to attract customers, profit on repeat orders\n\n✅ Test: Try 2 different price points for one week each and see which sells more." },
        { id: "4-7", title: "Getting Your First 100 Customers", duration: "22 min", content: "Your first customers are the hardest — and the most important.\n\n📋 Week-by-week plan:\n\nWeek 1: Friends & Family\n• Tell everyone you know\n• Give 5 free/discounted samples for honest reviews\n• Ask for WhatsApp contact sharing\n\nWeek 2: Local Community\n• Join WhatsApp groups in your area\n• Post in local Facebook groups\n• Approach local shops for collaboration\n\nWeek 3: Digital Presence\n• Post every day on Instagram\n• Go Live at least once showing your process\n\nWeek 4: Referral Program\n• 'Refer a friend, get ₹20 off your next order'\n• Ask happy customers for Google Reviews\n\n🎯 Target: 100 customers in 30 days is achievable!" },
        { id: "4-8", title: "Building Customer Loyalty", duration: "15 min", content: "Keeping a customer is 5x cheaper than finding a new one.\n\n✅ Loyalty strategies:\n• Remember their preferences and birthdays\n• Consistent quality — NEVER compromise\n• Quick response to WhatsApp messages (under 1 hour)\n• Surprise them: Extra portion, handwritten thank-you note\n• Create a loyalty program: '10th order FREE'\n\n📱 WhatsApp groups for customers:\n• Create a 'CMM Customers' broadcast list\n• Share new products, seasonal offers, behind-the-scenes\n• Poll them: 'Which flavour should I make next?'\n\n💡 A customer who refers 3 friends is worth ₹10,000+ to your business!" },
        { id: "4-9", title: "Handling Complaints Gracefully", duration: "12 min", content: "Every complaint is an opportunity to build trust.\n\n✅ The 4-step complaint response:\n1. LISTEN: Let them finish without interrupting\n2. APOLOGIZE: Even if it's not fully your fault\n3. SOLVE: Replace product, refund, or offer discount\n4. FOLLOW-UP: Check in 2 days later\n\n💡 Response template:\n'Hello [Name], I'm so sorry to hear this! This is not the quality I aim for. Please send me a photo so I can understand the issue. I'll [replace/refund] immediately. Your trust means everything to me 🙏'\n\n⚠️ Never argue with a customer on WhatsApp or public groups. One negative review can cost you 10 customers!" },
        { id: "4-10", title: "Word-of-Mouth Marketing", duration: "15 min", content: "Word-of-mouth is the most powerful and FREE marketing tool.\n\n✅ How to trigger word-of-mouth:\n• Deliver more than expected (over-pack, add a small extra)\n• Make the unboxing special (nice packaging, handwritten note)\n• Create a memorable story about your product\n• Ask happy customers to share a photo on their WhatsApp status\n\n📱 WhatsApp Status sharing:\n• Ask customers: 'If you loved it, could you share a photo on your status? It helps a lot!'\n• Most happy customers will do it — reaching 200+ people at once\n\n💡 Goal: Get 20% of your customers to refer at least 1 friend. That's 100% growth every few months!" },
        { id: "4-11", title: "Running Offers & Promotions", duration: "18 min", content: "Strategic promotions boost sales during slow periods.\n\n📋 Types of promotions that work:\n\n🌟 Festival Offers: Diwali, Ugadi, Sankranti — premium gift packs\n🛒 Bulk Discounts: 'Buy 3, get 10% off'\n⏰ Flash Sale: '24-hour offer — 20% off today only!'\n👥 Referral Offer: 'Refer a friend, you both get ₹50 off'\n📦 Free Delivery: 'Free delivery on orders above ₹500'\n\n⚠️ Rules for promotions:\n• Always have a clear end date\n• Make sure you're still profitable after discount\n• Don't discount too often — it devalues your product\n\n💡 Best time for promotions: Sunday evenings and festival weeks!" },
        { id: "4-12", title: "Module Quiz & Review", duration: "12 min", content: "🎉 Module 4 Complete — You're a Marketing Master!\n\n📝 Quick Quiz:\n1. What are the 4 letters of the AIDA formula?\n2. How many contacts can you message in one WhatsApp Broadcast?\n3. What is the best time of day for product photography?\n4. Name 3 types of promotions that work for home businesses.\n\n✅ Answers:\n1. Attention, Interest, Desire, Action\n2. 256 contacts per broadcast list\n3. Morning 10am-12pm in natural window light\n4. Festival offers, bulk discounts, referral offers (any 3 from the list)\n\n🚀 Next: Module 5 — Scaling & Growth!" },
      ]
    },
    {
      id: 5, title: "Scaling & Growth", icon: "🚀", lessonCount: 8, duration: "3.5 hours", level: "advanced",
      desc: "Take your business to the next level — hire, automate, and expand your market reach.",
      topics: ["Hiring your first helper", "Bulk orders and B2B", "Online marketplace presence", "Getting bank loans for growth"],
      lessons: [
        { id: "5-1", title: "Is Your Business Ready to Scale?", duration: "18 min", content: "Scaling too early can destroy a business. Know when you're ready.\n\n✅ Signs you're ready to scale:\n• Consistently profitable for 3+ months\n• More demand than you can supply alone\n• Processes are repeatable and documentable\n• Emergency fund of 3 months expenses\n• Clear understanding of unit economics\n\n❌ Signs you're NOT ready:\n• Still figuring out your pricing\n• Inconsistent product quality\n• No savings\n• Customer complaints unresolved\n\n📋 The Scaling Checklist:\n□ Monthly profit > ₹15,000\n□ 50+ regular customers\n□ Written down process for making your product\n□ 3 months expenses in savings\n\nCheck all 4? You're ready! ✅" },
        { id: "5-2", title: "Hiring Your First Helper", duration: "22 min", content: "Hiring help is scary but necessary to grow.\n\n✅ When to hire:\n• You're turning down orders due to lack of time\n• You spend more time on production than business\n• You're burning out\n\n📋 Hiring process:\n1. Write down exactly what tasks you need help with\n2. Find helpers: Neighbours, family, local women's groups\n3. Start with part-time (2-4 hours/day)\n4. Train them with your exact process\n5. Pay fairly: ₹200-400/day is standard\n\n⚠️ Legal note: For regular employees, you should register under the Shops & Establishment Act and contribute to ESI/PF if employing 10+ people.\n\n💡 Start with ONE helper. Train them perfectly. Then hire more." },
        { id: "5-3", title: "Managing Inventory at Scale", duration: "20 min", content: "When orders grow, inventory management becomes critical.\n\n📋 Basic inventory system:\n• Track RAW MATERIALS: What you have, what you need\n• Track FINISHED GOODS: What's ready to ship\n• Reorder Point: Order more when stock drops below X units\n\n✅ Free tools:\n• Google Sheets inventory tracker\n• Vyapar app (₹2,000/year, excellent for small businesses)\n• Physical stock register\n\n📊 Key metrics:\n• Stock Turn Rate: How fast you sell your inventory\n• Wastage Rate: How much you're throwing away\n• Reorder Frequency: How often you need to restock\n\n💡 Goal: Never run out of your top 3 selling products!" },
        { id: "5-4", title: "Getting Bulk Orders & B2B Clients", duration: "25 min", content: "Bulk orders = more income with less marketing effort.\n\n📋 Who to target for bulk orders:\n• Corporate offices (for gifting)\n• Wedding planners and caterers\n• Local shops and supermarkets\n• Hotels and restaurants\n• NGOs and government programs\n• Other resellers\n\n✅ How to pitch:\n1. Create a wholesale price list (15-25% below retail)\n2. Offer sample packs to test\n3. Minimum order: 10 units for first order\n4. Provide invoice (even handwritten is fine)\n5. Delivery within 3-5 days\n\n💌 WhatsApp pitch template:\n'Hello! I'm [Name] from [Business]. We make [Product] — all handmade, no preservatives. I'd love to offer you a bulk pricing proposal. Can I share our catalog?'" },
        { id: "5-5", title: "Expand to Online Marketplaces", duration: "22 min", content: "Online platforms can bring you customers from across India.\n\n📋 Platforms to consider:\n\n1. Community Makers' Market — Sell locally, connect via WhatsApp\n2. Meesho — Easy to list, 0% commission, 35M+ buyers\n3. Amazon Local Selling — Premium market, better margins\n4. Instagram Shopping — Tag products in posts\n5. Flipkart — High volume, competitive\n\n✅ Start with:\n• Community Makers' Market (free, direct WhatsApp contact)\n• Meesho (easiest for beginners, free to join)\n\n📋 What you need to sell online:\n• Good product photos (5+ per product)\n• Clear description with weight, size, shelf life\n• Fast packaging (ship within 48 hours)\n• Return policy" },
        { id: "5-6", title: "Getting Bank Loans for Growth", duration: "20 min", content: "At the growth stage, you may need ₹1-10 Lakhs to scale up.\n\n📋 Loan options by stage:\n\nStage 1 (< ₹1L needed): MUDRA Shishu\nStage 2 (₹1-5L needed): MUDRA Kishore / PM Vishwakarma\nStage 3 (₹5-10L needed): MUDRA Tarun / Mahila Udyam Nidhi\nStage 4 (> ₹10L needed): MSME Business Loan\n\n✅ How to increase your loan eligibility:\n• File ITR for 2+ years\n• Maintain good bank transaction history\n• Have Udyam Registration\n• Prepare a proper business plan\n• Maintain CIBIL score above 650\n\n💡 Apply for a small loan first (₹50,000), repay on time, then apply for more. This builds your credit history!" },
        { id: "5-7", title: "Building Your Brand", duration: "22 min", content: "A strong brand makes customers remember you and pay premium prices.\n\n📋 Brand elements:\n\n1. NAME: Memorable, easy to spell, reflects your product\n2. LOGO: Simple, works in black & white, hire on Fiverr for ₹500-1,000\n3. COLOURS: Choose 2-3 brand colours and use consistently\n4. TAGLINE: One sentence that captures your value\n5. STORY: Why you started, what makes you different\n\n💡 Brand Story Example:\n'Amma's Kitchen started in my home kitchen with my grandmother's secret gongura recipe. Three generations of love, zero preservatives. Every jar is made fresh, with the same care as cooking for family.'\n\n✅ Apply consistently on:\n• Product labels\n• WhatsApp Business profile\n• Instagram page\n• Packaging and bags" },
        { id: "5-8", title: "Module Quiz & Final Review", duration: "15 min", content: "🎉 CONGRATULATIONS! You've completed all 5 modules!\n\n🏆 You are now a Certified Community Makers' Market Entrepreneur!\n\n📝 Final Quiz:\n1. Name 4 signs that your business is ready to scale.\n2. What is the easiest online marketplace for beginners?\n3. What loan stage should you start with if you need ₹50,000?\n4. Name 3 types of bulk order clients you can target.\n\n✅ Answers:\n1. Consistently profitable 3+ months, more demand than supply, repeatable process, 3-month savings\n2. Meesho (or Community Makers' Market)\n3. MUDRA Shishu loan\n4. Corporate offices, wedding planners, local shops, hotels (any 3)\n\n🌟 YOUR NEXT STEPS:\n□ Register on Community Makers' Market\n□ List your first product\n□ Apply for Udyam Registration\n□ Start your WhatsApp Business catalog\n□ Set your 30-day sales target\n\nYou've got this! 🚀" },
      ]
    },
  ],

  // ── EVENTS ──────────────────────────────────
  events: [
    { id: 1, title: "WhatsApp Business Masterclass", date: "June 15, 2026", time: "10:00 AM", type: "online", host: "Digital Guru Ravi", attendees: 143 },
    { id: 2, title: "Hyderabad Makers' Fair 2026", date: "June 22, 2026", time: "9:00 AM", type: "offline", host: "CMM Community", attendees: 320 },
    { id: 3, title: "Mudra Loan Application Workshop", date: "June 28, 2026", time: "11:00 AM", type: "online", host: "Govt. Partner", attendees: 89 },
    { id: 4, title: "Packaging & Branding on ₹500", date: "July 5, 2026", time: "3:00 PM", type: "online", host: "Priya Designs", attendees: 211 },
  ],
};
